layout_spectrum: 0.6218638
typography_spectrum: 0.7921147
color:
  saturation: 0.6451613
  brandStrength: 0.2277716
  lightness: 0.559413
  brandColors:
    - '#010104'
    - '#FDFCFA'
    - '#0288E9'
    - '#BDB59A'
    - '#0103E0'
  rhythmicContrast: 0.8100358
name: Mind Therapy London
